apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-service   # deployment 이름 
  namespace: spam-namespace
  labels:
    app: spam-service  # Deployment에 app=member-service 라벨 추가 (서비스와 매칭될 때 사용)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spam-service  # 이 Deployment가 관리할 Pod들의 라벨 지정 (Pod template의 labels와 일치해야 함)
  template:
    metadata:
      labels:
        app: spam-service  # 생성될 Pod에 app=member-service 라벨 추가 (Service가 이 라벨을 보고 연결)
    spec:
      containers:
        - name: spam-service  # 컨테이너 이름
          image: team04registry.azurecr.io/spam-service:latest  # 사용할 컨테이너 이미지 (ACR에서 가져옴)
          ports:
            - containerPort: 8080
          # resources: 
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "256Mi"
          #     cpu: "250m"
